services:
  - type: web
    name: demarq
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data/constructor.db
      - key: NODE_VERSION
        value: 22.15.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
